cita_index:
    path:     /
    defaults: { _controller: "AngelHospitalBundle:Cita:index" }
    methods:  GET

cita_show:
    path:     /{id}/show
    defaults: { _controller: "AngelHospitalBundle:Cita:show" }
    methods:  GET

cita_new:
    path:     /new
    defaults: { _controller: "AngelHospitalBundle:Cita:new" }
    methods:  [GET, POST]

cita_edit:
    path:     /{id}/edit
    defaults: { _controller: "AngelHospitalBundle:Cita:edit" }
    methods:  [GET, POST]

cita_delete:
    path:     /{id}/delete
    defaults: { _controller: "AngelHospitalBundle:Cita:delete" }
    methods:  DELETE

