paciente_index:
    path:     /
    defaults: { _controller: "AngelHospitalBundle:Paciente:index" }
    methods:  GET

#pedirCitaAction:
#    path:     /cita
#    defaults: { _controller: "AngelHospitalBundle:Paciente:solicitarCita" }
#    methods:  GET
 
paciente_show:
    path:     /{id}/show
    defaults: { _controller: "AngelHospitalBundle:Paciente:show" }
    methods:  GET

paciente_new:
    path:     /new
    defaults: { _controller: "AngelHospitalBundle:Paciente:new" }
    methods:  [GET, POST]

paciente_edit:
    path:     /{id}/edit
    defaults: { _controller: "AngelHospitalBundle:Paciente:edit" }
    methods:  [GET, POST]

paciente_delete:
    path:     /{id}/delete
    defaults: { _controller: "AngelHospitalBundle:Paciente:delete" }
    methods:  DELETE
